language: python
python:
- '2.7.11'
- '3.5.2'
install:
- pip install --upgrade pip
- pip install --upgrade setuptools
- pip install -r requirements.txt
- pip install .
scripts:
- py.test tests
env:
- NUMBER_OF_CPUS=1
after_success:
- coveralls
