language: python
python:
- '2.7.11'
- '3.5.2'
install:
- pip install --upgrade pip
- pip install --upgrade setuptools
- pip install coveralls
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install .
script:
- py.test tests
after_success:
- coveralls
